// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWLKMtUtuEaBJ63UozEBksE-jkHaQJG8',
    appId: '1:945103112875:android:36edc42397563fab0105ee',
    messagingSenderId: '945103112875',
    projectId: 'disaster-mini-project',
    storageBucket: 'disaster-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBbn2yyFh02zJYueOmsXSMr2EZteZPwA',
    appId: '1:945103112875:ios:178a03cd6bf4e6ad0105ee',
    messagingSenderId: '945103112875',
    projectId: 'disaster-mini-project',
    storageBucket: 'disaster-mini-project.appspot.com',
    androidClientId: '945103112875-vvklbbps5tg07bgk1mnpp05fnp3a92b0.apps.googleusercontent.com',
    iosClientId: '945103112875-ndioinu24m4mdp63kqknu4l6s1un6gb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.disasterAdmin',
  );
}
